"""create knowledge base document chunk tables

Revision ID: 324858d0664b
Revises: 
Create Date: 2026-06-15 23:06:06.874840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '324858d0664b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_create_at', 'knowledge_bases', ['created_at'], unique=False)
    op.create_index('idx_kb_name_active', 'knowledge_bases', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_kb_status', 'knowledge_bases', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_ext', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('process_started_at', sa.DateTime(), nullable=True),
    sa.Column('process_finished_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_doc_file_hash', 'documents', ['file_hash'], unique=False)
    op.create_index('idx_doc_kb_id', 'documents', ['knowledge_base_id'], unique=False)
    op.create_index('idx_doc_status', 'documents', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('cotent', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('splitter_name', sa.String(), nullable=True),
    sa.Column('splitter_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_status', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('qdrant_collection', sa.String(), nullable=True),
    sa.Column('qdrant_point_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uk_chunk_doc_index')
    )
    op.create_index('idx_chunk_doc_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_embedding_status', 'document_chunks', ['embedding_status'], unique=False)
    op.create_index('idx_chunk_kb_id', 'document_chunks', ['knowledge_base_id'], unique=False)
    op.create_index('idx_chunk_qdrant_point_id', 'document_chunks', ['qdrant_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunk_qdrant_point_id', table_name='document_chunks')
    op.drop_index('idx_chunk_kb_id', table_name='document_chunks')
    op.drop_index('idx_chunk_embedding_status', table_name='document_chunks')
    op.drop_index('idx_chunk_doc_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_doc_status', table_name='documents')
    op.drop_index('idx_doc_kb_id', table_name='documents')
    op.drop_index('idx_doc_file_hash', table_name='documents')
    op.drop_index('idx_doc_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_kb_status', table_name='knowledge_bases')
    op.drop_index('idx_kb_name_active', table_name='knowledge_bases', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_kb_create_at', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
